/*
 * Copyright 2010 sasc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sasc.terminal;

import java.io.ByteArrayOutputStream;
import java.util.Arrays;
import sasc.emv.DOL;
import sasc.emv.EMVTags;
import sasc.emv.TagAndLength;
import sasc.util.Util;

/**
 * TODO move values to external (properties) file
 * @author sasc
 */
public class TerminalProfile {

    private final static byte[] TERMINAL_COUNTRY_CODE = new byte[]{(byte) 0x08, (byte) 0x26};
    private final static byte[] TRANSACTION_CURRENCY_CODE = new byte[]{(byte) 0x08, (byte) 0x26};

    //TODO
    //Default Dynamic Data Authentication Data Object List (DDOL)
    //DDOL to be used for constructing the INTERNAL AUTHENTICATE command if the DDOL in the card is not present
    //Default Transaction Certificate Data Object List (TDOL)
    //TDOL to be used for generating the TC Hash Value if the TDOL in the card is not present
    public static byte[] getTerminalResidentData(TagAndLength tal) {
        if (tal.getTag().equals(EMVTags.TERMINAL_COUNTRY_CODE)) { //TODO && tal.getLength() == TERMINAL_COUNTRY_CODE.length ??
            return TERMINAL_COUNTRY_CODE;
        } else if (tal.getTag().equals(EMVTags.TRANSACTION_CURRENCY_CODE)) {
            return TRANSACTION_CURRENCY_CODE;
        }
        byte[] defaultResponse = new byte[tal.getLength()];
        Arrays.fill(defaultResponse, (byte) 0x00);
        return defaultResponse;
    }

    //TODO move somewhere else
    public static byte[] constructDOLResponse(DOL dol) {
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        for (TagAndLength tagAndLength : dol.getTagAndLengthList()) {
            byte[] data = getTerminalResidentData(tagAndLength);
            stream.write(data, 0, data.length);
        }
        return stream.toByteArray();
    }

    //The ICC may contain the DDOL, but there shall be a default DDOL in the terminal, 
    //specified by the payment system, for use in case the DDOL is not present in the ICC.
    public static byte[] getDefaultDDOL() {
        //It is mandatory that the DDOL contains the Unpredictable Number generated by the terminal (tag '9F37', 4 bytes binary).
        byte[] unpredictableNumber = Util.generateRandomBytes(4);
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
